name: Reactant
main: dev.reactant.reactant.core.ReactantCore
version: 0.2.4
api-version: "1.17"
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.20
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.20
  - org.jetbrains.kotlin:kotlin-reflect:1.5.20
  - io.reactivex.rxjava3:rxjava:3.0.13
  - io.reactivex.rxjava3:rxkotlin:3.0.1
  - org.reflections:reflections:0.9.11
  - com.google.code.gson:gson:2.8.7
  - org.yaml:snakeyaml:1.26
  - com.moandjiezana.toml:toml4j:0.7.2
  - info.picocli:picocli:4.3.2
  - org.mariadb.jdbc:mariadb-java-client:2.5.1
  - org.apache.logging.log4j:log4j-core:2.12.1
  - com.squareup.retrofit2:retrofit:2.9.0
  - com.squareup.retrofit2:adapter-rxjava3:2.9.0
  - com.squareup.retrofit2:converter-gson:2.9.0
  - net.sourceforge.cssparser:cssparser:0.9.27
  - javassist:javassist:3.12.1.GA